# Generated by Django 4.2.3 on 2023-09-04 12:33
from typing import List

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies: List[str] = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("birthday", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContactDataType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="email", max_length=20)),
                (
                    "regex_pattern",
                    models.CharField(
                        default="^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$",
                        help_text="Regular expression pattern for validation",
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ContactData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=255)),
                ("contact", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="phone_book.contact")),
                (
                    "contact_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="phone_book.contactdatatype"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contact",
            name="groups",
            field=models.ManyToManyField(to="phone_book.group"),
        ),
    ]
