# Generated by Django 4.2.5 on 2023-09-14 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("phone_book", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={"verbose_name": "Группа", "verbose_name_plural": "Группы"},
        ),
        migrations.AlterField(
            model_name="contactdata",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_data",
                to="phone_book.contact",
                verbose_name="Контактные данные",
            ),
        ),
        migrations.AlterField(
            model_name="contactdata",
            name="contact_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="phone_book.contacttype",
                verbose_name="Тип данных",
            ),
        ),
        migrations.AlterField(
            model_name="contacttype",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Тип данных"),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Имя"),
        ),
    ]
