# Generated by Django 4.2.3 on 2023-09-04 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("phone_book", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name="contact",
            options={"verbose_name": "Контакт", "verbose_name_plural": "Контакты"},
        ),
        migrations.RemoveField(
            model_name="contact",
            name="birthday",
        ),
        migrations.RemoveField(
            model_name="contactdata",
            name="contact",
        ),
        migrations.AddField(
            model_name="contact",
            name="birthdate",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
        migrations.AddField(
            model_name="contact",
            name="contact_data",
            field=models.ManyToManyField(to="phone_book.contactdata", verbose_name="Контактные данные"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="groups",
            field=models.ManyToManyField(to="phone_book.group", verbose_name="Группы"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="contactdata",
            name="contact_type",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="phone_book.contacttype"),
        ),
        migrations.DeleteModel(
            name="ContactDataType",
        ),
    ]
