# Generated by Django 4.2.5 on 2023-09-13 12:03
from typing import List

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies: List[str] = []

    operations = [
        migrations.CreateModel(
            name="GameRoom",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("current_state", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("guessed_letters", models.CharField(default="", max_length=26)),
            ],
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlayerGameRoom",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("game_room", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="game_word.gameroom")),
                ("player", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="game_word.player")),
            ],
        ),
        migrations.AddField(
            model_name="gameroom",
            name="players",
            field=models.ManyToManyField(through="game_word.PlayerGameRoom", to="game_word.player"),
        ),
        migrations.AddField(
            model_name="gameroom",
            name="word_to_guess",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="game_word.word"),
        ),
    ]
